# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 09:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('message', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Veuiller donner un téléphone valide', regex='^\\d{10}$')])),
                ('ville', models.CharField(max_length=90)),
                ('rue', models.CharField(max_length=120)),
                ('numero_de_la_voie', models.PositiveIntegerField()),
                ('code_postal', models.IntegerField(validators=[django.core.validators.RegexValidator(code='Invalid postal', message='Veuiller donner un code postal valide', regex='^\\d{5}$')])),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demende')),
            ],
        ),
    ]
